import type { Metadata } from "next";
import { Header } from "@/components/header";
import { ProtectedRoute } from "@/components/ProtectedRoute";
import { UserProvider } from "@/hooks/UserContext";

export const metadata: Metadata = {
  title: "FinDash",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <ProtectedRoute>
        <Header />
        {children}
      </ProtectedRoute>
    </UserProvider>
  );
}
